package rpgboss.model

/**
 * These locations are given with the top-left of the map being at (0, 0).
 * This means that the center of the tiles are actually at 0.5 intervals. 
 */
case class MapLoc(map: Int, x: Float, y: Float)

case class SpriteSpec(spriteset: String, spriteindex: Int) 

case class Actor(defaultName: String,
                 sprite: SpriteSpec)
               
                 
case class ProjectData(title: String, 
                       recentMapId: Int = -1,
                       startingLoc: MapLoc = MapLoc(0, 5.5f, 5.5f),
                       
                       actors: Array[Actor] = ProjectData.defaultActors,
                       
                       autotiles: Array[String] = ProjectData.defaultAutotiles,
                       
                       titlePic: String = "LordSpirit.jpg",
                       startingParty: Array[Int] = Array(0),
                       
                       windowskin: String = "LastPhantasmScanlines.png",
                       msgfont: String = "Vera.ttf",
                       fontsize: Int = 24,
                       soundCursor: String = "MenuCursor.wav",
                       soundSelect: String = "MenuSelect.wav",
                       soundCancel: String = "MenuCancel.wav",
                       soundCannot: String = "MenuCannot.wav"
                       )

object ProjectData {
  def defaultActors = Array(
    Actor("Pando", SpriteSpec("vx_chara01_a.png", 4)),
    Actor("Estine", SpriteSpec("vx_chara01_a.png", 1)),
    Actor("Leoge", SpriteSpec("vx_chara01_a.png", 3)),
    Actor("Graven", SpriteSpec("vx_chara01_a.png", 2)),
    Actor("Carona", SpriteSpec("vx_chara01_a.png", 6))
  )
  
  def defaultAutotiles = Array(
    "Refmap-A1-0-0-A.png",
    "Refmap-A1-0-0-B.png",
    "Refmap-A1-0-1-A.png",
    "Refmap-A1-0-1-B.png",
    "Refmap-A1-1-0-A.png",
    "Refmap-A1-1-0-B.png",
    "Refmap-A1-1-1-A.png",
    "Refmap-A1-1-1-B.png",
    "Refmap-A1-2-0-A.png",
    "Refmap-A1-2-0-B.png",
    "Refmap-A1-2-1-A.png",
    "Refmap-A1-2-1-B.png",
    "Refmap-A1-3-0-A.png",
    "Refmap-A1-3-0-B.png",
    "Refmap-A1-3-1-A.png",
    "Refmap-A1-3-1-B.png",
    "Refmap-A2-0-0.png",
    "Refmap-A2-0-1.png",
    "Refmap-A2-0-2.png",
    "Refmap-A2-0-3.png",
    "Refmap-A2-0-4.png",
    "Refmap-A2-0-5.png",
    "Refmap-A2-0-6.png",
    "Refmap-A2-0-7.png",
    "Refmap-A2-1-0.png",
    "Refmap-A2-1-1.png",
    "Refmap-A2-1-2.png",
    "Refmap-A2-1-3.png",
    "Refmap-A2-1-4.png",
    "Refmap-A2-1-5.png",
    "Refmap-A2-1-6.png",
    "Refmap-A2-1-7.png",
    "Refmap-A2-2-0.png",
    "Refmap-A2-2-1.png",
    "Refmap-A2-2-2.png",
    "Refmap-A2-2-3.png",
    "Refmap-A2-2-4.png",
    "Refmap-A2-2-5.png",
    "Refmap-A2-2-6.png",
    "Refmap-A2-2-7.png",
    "Refmap-A2-3-0.png",
    "Refmap-A2-3-1.png",
    "Refmap-A2-3-2.png",
    "Refmap-A2-3-3.png",
    "Refmap-A2-3-4.png",
    "Refmap-A2-3-5.png",
    "Refmap-A2-3-6.png",
    "Refmap-A2-3-7.png",
    "Refmap-A3-0-0-A.png",
    "Refmap-A3-0-1-A.png",
    "Refmap-A3-0-2-A.png",
    "Refmap-A3-0-3-A.png",
    "Refmap-A3-0-4-A.png",
    "Refmap-A3-0-5-A.png",
    "Refmap-A3-0-6-A.png",
    "Refmap-A3-0-7-A.png",
    "Refmap-A3-1-0-A.png",
    "Refmap-A3-1-1-A.png",
    "Refmap-A3-1-2-A.png",
    "Refmap-A3-1-3-A.png",
    "Refmap-A3-1-4-A.png",
    "Refmap-A3-1-5-A.png",
    "Refmap-A3-1-6-A.png",
    "Refmap-A3-1-7-A.png",
    "Refmap-A3-2-0-A.png",
    "Refmap-A3-2-1-A.png",
    "Refmap-A3-2-2-A.png",
    "Refmap-A3-2-3-A.png",
    "Refmap-A3-2-4-A.png",
    "Refmap-A3-2-5-A.png",
    "Refmap-A3-2-6-A.png",
    "Refmap-A3-2-7-A.png",
    "Refmap-A3-3-0-A.png",
    "Refmap-A3-3-1-A.png",
    "Refmap-A3-3-2-A.png",
    "Refmap-A3-3-3-A.png",
    "Refmap-A3-3-4-A.png",
    "Refmap-A3-3-5-A.png",
    "Refmap-A3-3-6-A.png",
    "Refmap-A3-3-7-A.png",
    "Refmap-A4-0-0.png",
    "Refmap-A4-0-1.png",
    "Refmap-A4-0-2.png",
    "Refmap-A4-0-3.png",
    "Refmap-A4-0-4.png",
    "Refmap-A4-0-5.png",
    "Refmap-A4-0-6.png",
    "Refmap-A4-0-7.png",
    "Refmap-A4-1-0.png",
    "Refmap-A4-1-1.png",
    "Refmap-A4-1-2.png",
    "Refmap-A4-1-3.png",
    "Refmap-A4-1-4.png",
    "Refmap-A4-1-5.png",
    "Refmap-A4-1-6.png",
    "Refmap-A4-1-7.png",
    "Refmap-A4-2-0.png",
    "Refmap-A4-2-1.png",
    "Refmap-A4-2-2.png",
    "Refmap-A4-2-3.png",
    "Refmap-A4-2-4.png",
    "Refmap-A4-2-5.png",
    "Refmap-A4-2-6.png",
    "Refmap-A4-2-7.png",
    "Refmap-A4-3-0.png",
    "Refmap-A4-3-1.png",
    "Refmap-A4-3-2.png",
    "Refmap-A4-3-3.png",
    "Refmap-A4-3-4.png",
    "Refmap-A4-3-5.png",
    "Refmap-A4-3-6.png",
    "Refmap-A4-3-7.png",
    "Refmap-A4-4-0.png",
    "Refmap-A4-4-1.png",
    "Refmap-A4-4-2.png",
    "Refmap-A4-4-3.png",
    "Refmap-A4-4-4.png",
    "Refmap-A4-4-5.png",
    "Refmap-A4-4-6.png",
    "Refmap-A4-4-7.png",
    "Refmap-A4-5-0.png",
    "Refmap-A4-5-1.png",
    "Refmap-A4-5-2.png",
    "Refmap-A4-5-3.png",
    "Refmap-A4-5-4.png",
    "Refmap-A4-5-5.png",
    "Refmap-A4-5-6.png",
    "Refmap-A4-5-7.png"
  )
}
